imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:

    dependencies:
        before:
            -
                command: "mkdir build"
        after:
            - "make test"

    tests:
        override:
            -
                command: "vendor/bin/phpunit --configuration .phpunit.xml"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"

